### ISSUE TITLE
Why force the runloop?

### ISSUE THREAD

**Issue by bcardarella** [ride/ember-stripe-service#19]
I'm wondering why https://github.com/ride/ember-stripe-service/blob/master/app/services/stripe.js#L12 exists

**Comment by buritica** [comment]
Because I couldn't get the normal run loop to work, promise would resolve before getting the Stripe token. Hit myself against many, many walls and this made it work. More info can be found https://github.com/ride/ember-stripe-service/pull/10

**Comment by bcardarella** [comment]
@rwjblue can you confirm/deny if this is a thing and any advice on how I can go about patching?

**Comment by buritica** [comment]
hey @bcardarella, you can now see in #27 what happens when the low-level `Ember.run.begin()` is removed. 

- unit tests with stubbed Stripe pass
- [integration tests](https://github.com/ride/ember-stripe-service/blob/master/tests/integration/stripe-test.js) fail

so, "this is a thing", and I'm not pretty sure how to solve it or why it happens, but any suggestions are welcome because I think this is also messing up other people's tests

**Comment by buritica** [comment]
This now works, thanks for the feedback!
